# Generated by Django 5.2.1 on 2025-06-03 17:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('doctor_id', models.UUIDField(db_index=True)),
                ('nurse_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('appointment_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('CANCELLED_PATIENT', 'Cancelled by Patient'), ('CANCELLED_STAFF', 'Cancelled by Staff'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20)),
                ('reason_for_visit', models.TextField(blank=True, null=True)),
                ('notes_patient', models.TextField(blank=True, null=True)),
                ('notes_staff', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_id', models.UUIDField(db_index=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
