# Generated by Django 5.2.2 on 2025-06-05 03:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('record_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB_RESULT', 'Lab Result'), ('PRESCRIPTION', 'Prescription'), ('DIAGNOSIS', 'Diagnosis'), ('ALLERGY', 'Allergy'), ('VACCINATION', 'Vaccination'), ('NOTE', 'Note')], max_length=50)),
                ('appointment_id', models.UUIDField(blank=True, null=True)),
                ('created_by_user_id', models.UUIDField()),
                ('record_time', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField()),
                ('is_sensitive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecordVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_by_user_id', models.UUIDField()),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('previous_details', models.JSONField()),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='medical_record.medicalrecord')),
            ],
        ),
    ]
